from simplaceity import *
ctx = PyContext()
c_and = ctx.addCellType("AND")
c_and.setSize(20, 100)
c_and.addPort("A", PortDir.IN)
c_and.setPortOffset("A", 0, 20)
c_and.addPort("B", PortDir.IN)
c_and.setPortOffset("B", 0, 40)
c_and.addPort("Q", PortDir.OUT)
c_and.setPortOffset("Q", 20, 20)

c_not = ctx.addCellType("NOT")
c_not.setSize(20, 50)
c_not.addPort("A", PortDir.IN)
c_not.setPortOffset("A", 0, 20)
c_not.addPort("Q", PortDir.OUT)
c_not.setPortOffset("Q", 20, 20)

c_top = ctx.addCellType("top")
m_top = c_top.intoModule()
a1 = m_top.addInst("and_1", "AND")
a2 = m_top.addInst("and_2", "AND")
n1 = m_top.addInst("n1", "NOT")
a1.connectPort("A", "i0")
a1.connectPort("B", "i1")
a1.connectPort("Q", "q0")
n1.connectPort("A", "q0")
n1.connectPort("Q", "qn0")
a2.connectPort("A", "i2")
a2.connectPort("B", "qn0")
a2.connectPort("Q", "q")
